image: node:lts-stretch

pages:
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
  only:
    - master
  script:
    - python --version
    - pip install -U -r requirements.txt
    - mv src/ public/
