image: node:lts-stretch

stages:
  - build

build:
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
  only:
    - master
  script:
    - yarn install --production --ignore-optional --ignore-scripts --pure-lockfile --non-interactive
    - node index.js
    - mkdir public
    - cp index.py public/index.pyw
    - cp favicon.ico public/favicon.ico
    - python --version
  stage: build
