image: node:lts-stretch

pages:
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
  only:
    - master
  script:
    - python --version
    - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - python get-pip.py
    - pip install -U -r requirements.txt
    - mv src/ public/
