name: Lint and run

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: pip3 install pylint
    - run: bash linter.sh
